### PR TITLE
Test fresh stack builds

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
@lsh-0 see the different checks:
- `pr-head` (the whole PR)
- `pr-base` (the `master` version of the stack)
- `pr-fresh` (building from scratch)
- `pr-update` (applying this change to the base)

**Comment by lsh-0** [comment]
nice work.

I can see the fresh build updating the medium formula to a specific revision:
```
[54.173.63.201] put: /ext/srv/builder/scripts/update-master-formula.sh -> /tmp/update-master-formula.sh-20171206161055
[54.173.63.201] sudo: /bin/bash /tmp/update-master-formula.sh-20171206161055 'medium-formula' 'https://github.com/elifesciences/medium-formula' '34b9b6428fc7a49ac9e4b01c55218990cf7958e3'
[54.173.63.201] out: HEAD is now at bc25fb3 Removing fictitious state
[54.173.63.201] out: Current branch master is up to date.
[54.173.63.201] out: Note: checking out '34b9b6428fc7a49ac9e4b01c55218990cf7958e3'.
[54.173.63.201] out: 
[54.173.63.201] out: You are in 'detached HEAD' state. You can look around, make experimental
[54.173.63.201] out: changes and commit them, and you can discard any commits you make in this
[54.173.63.201] out: state without impacting any branches by performing another checkout.
[54.173.63.201] out: 
[54.173.63.201] out: If you want to create a new branch to retain commits you create, you may
[54.173.63.201] out: do so (now or later) by using -b with the checkout command again. Example:
[54.173.63.201] out: 
[54.173.63.201] out:   git checkout -b new_branch_name
[54.173.63.201] out: 
[54.173.63.201] out: HEAD is now at 34b9b64... Test fresh stack builds
[54.173.63.201] out: 

[54.173.63.201] sudo: rm /tmp/update-master-formula.sh-20171206161055
```

I really should rename `update-master-formula.sh` though, since I'm using it outside the master server these days.

**Review by lsh-0 — APPROVED** [review]
:1st_place_medal:

**Comment by giorgiosironi** [comment]
Closing this build as it's just a whitespace change to have a non-empty diff; the new `fresh` part of the formula builds will be applied automatically to all formula PRs.

**Pull request closed without merging**
